const express = require('express');

function createDocumentRoutes(context) {
  const { db, auth, admin, manager, isLeadership, isExecutive, asyncRoute, validHttpUrl, one, ids, activityScope, leadsTeam, belongsToTeam, canManageTeam, managedTeamIds, canManageUser, canManageActivity, visibleActivity, bcrypt, ExcelJS, packageInfo, logger, mailer, push, taskUpload, attachmentKinds, allowedExtensions, attachmentRoot, path, fs, crypto } = context;
  const router = express.Router();

router.get('/api/documents',auth,asyncRoute(async(req,res)=>{const q=`%${String(req.query.q||'').trim()}%`,year=String(req.query.year||'all'),teamId=String(req.query.team_id||'all'),user=req.session.user,visibilitySql=isExecutive(user)?`1=1`:`(d.visibility='all_teams' OR EXISTS(SELECT 1 FROM user_teams visible_membership WHERE visible_membership.user_id=? AND visible_membership.team_id=d.issuing_team_id))`,visibilityParams=isExecutive(user)?[]:[user.id],params=[...visibilityParams,q,q,year,year,teamId,teamId];const [[documents],[filterTeams],[issueTeams],[yearRows]]=await Promise.all([db.execute(`SELECT d.*,t.name team_name,t.color team_color,u.name creator_name FROM documents d JOIN teams t ON t.id=d.issuing_team_id JOIN users u ON u.id=d.created_by WHERE ${visibilitySql} AND (d.name LIKE ? OR d.description LIKE ?) AND (?='all' OR d.applicable_year=?) AND (?='all' OR d.issuing_team_id=?) ORDER BY d.applicable_year DESC,d.name`,params),db.execute(`SELECT id,name,color FROM teams t WHERE t.is_active=1 AND (${isExecutive(user)?'1=1':`EXISTS(SELECT 1 FROM documents d WHERE d.issuing_team_id=t.id AND (d.visibility='all_teams' OR EXISTS(SELECT 1 FROM user_teams vm WHERE vm.user_id=? AND vm.team_id=t.id)))`}) ORDER BY sort_order,name`,isExecutive(user)?[]:[user.id]),isExecutive(user)?db.execute('SELECT id,name,color FROM teams WHERE is_active=1 ORDER BY sort_order,name'):db.execute('SELECT t.id,t.name,t.color FROM user_teams ut JOIN teams t ON t.id=ut.team_id WHERE ut.user_id=? AND t.is_active=1 ORDER BY t.sort_order,t.name',[user.id]),db.execute(`SELECT DISTINCT d.applicable_year FROM documents d WHERE ${visibilitySql} ORDER BY d.applicable_year DESC`,visibilityParams)]);for(const document of documents)document.can_edit=isExecutive(user)||Number(document.created_by)===Number(user.id)||await belongsToTeam(user.id,document.issuing_team_id);res.json({documents,filterTeams,issueTeams,years:yearRows.map(x=>Number(x.applicable_year))})}));

router.post('/api/documents',auth,asyncRoute(async(req,res)=>{const name=String(req.body.name||'').trim(),linkUrl=String(req.body.link_url||'').trim(),description=String(req.body.description||'').trim(),year=Number(req.body.applicable_year),teamId=Number(req.body.issuing_team_id),visibility=String(req.body.visibility||'issuing_team');let parsed;try{parsed=new URL(linkUrl)}catch{}if(!name||name.length>200||!description||!parsed||!['http:','https:'].includes(parsed.protocol)||!Number.isInteger(year)||year<1900||year>2100||!Number.isInteger(teamId)||!['all_teams','issuing_team'].includes(visibility))return res.status(400).json({error:'Complete every document field with valid information.'});const [teams]=await db.execute('SELECT id FROM teams WHERE id=? AND is_active=1',[teamId]);if(!teams.length)return res.status(400).json({error:'The issuing team is unavailable.'});if(!isExecutive(req.session.user)){const [membership]=await db.execute('SELECT 1 FROM user_teams WHERE user_id=? AND team_id=?',[req.session.user.id,teamId]);if(!membership.length)return res.status(403).json({error:'You may only issue documents for your teams.'})}const [result]=await db.execute('INSERT INTO documents(name,link_url,description,applicable_year,issuing_team_id,visibility,created_by) VALUES(?,?,?,?,?,?,?)',[name,linkUrl,description,year,teamId,visibility,req.session.user.id]);res.status(201).json({id:result.insertId})}));
router.patch('/api/documents/:id',auth,asyncRoute(async(req,res)=>{const [existingRows]=await db.execute('SELECT * FROM documents WHERE id=?',[req.params.id]),existing=one(existingRows);if(!existing)return res.status(404).json({error:'Document not found.'});const user=req.session.user,canEdit=isExecutive(user)||Number(existing.created_by)===Number(user.id)||await belongsToTeam(user.id,existing.issuing_team_id);if(!canEdit)return res.status(403).json({error:'You cannot edit this document.'});const name=String(req.body.name||'').trim(),linkUrl=String(req.body.link_url||'').trim(),description=String(req.body.description||'').trim(),year=Number(req.body.applicable_year),teamId=Number(req.body.issuing_team_id),visibility=String(req.body.visibility||'issuing_team');let parsed;try{parsed=new URL(linkUrl)}catch{}if(!name||name.length>200||!description||!parsed||!['http:','https:'].includes(parsed.protocol)||!Number.isInteger(year)||year<1900||year>2100||!Number.isInteger(teamId)||!['all_teams','issuing_team'].includes(visibility))return res.status(400).json({error:'Complete every document field with valid information.'});const [teams]=await db.execute('SELECT id FROM teams WHERE id=? AND is_active=1',[teamId]);if(!teams.length)return res.status(400).json({error:'The issuing team is unavailable.'});if(!isExecutive(user)){const canIssueForTarget=await belongsToTeam(user.id,teamId);if(!canIssueForTarget)return res.status(403).json({error:'You may only issue documents for your teams.'})}await db.execute('UPDATE documents SET name=?,link_url=?,description=?,applicable_year=?,issuing_team_id=?,visibility=? WHERE id=?',[name,linkUrl,description,year,teamId,visibility,req.params.id]);res.json({ok:true})}));

  return router;
}

module.exports = { createDocumentRoutes };

