const express = require('express');

function createReportRoutes(context) {
  const { db, auth, admin, manager, isLeadership, asyncRoute, validHttpUrl, one, ids, activityScope, leadsTeam, belongsToTeam, canManageTeam, managedTeamIds, canManageUser, canManageActivity, visibleActivity, bcrypt, ExcelJS, packageInfo, logger, push, taskUpload, attachmentKinds, allowedExtensions, attachmentRoot, path, fs, crypto } = context;
  const router = express.Router();

router.get('/api/archive',auth,asyncRoute(async(req,res)=>{const q=`%${String(req.query.q||'')}%`,s=activityScope(req.actor);const [rows]=await db.execute(`SELECT a.*,te.name team_name,te.color team_color,u.name creator_name,GROUP_CONCAT(DISTINCT involved.name ORDER BY involved.name SEPARATOR ', ') team_names,COUNT(DISTINCT t.id) task_count,COUNT(DISTINCT t.id) done_count,COUNT(DISTINCT p.user_id) participant_count,MAX(n.created_at) last_update FROM activities a JOIN teams te ON te.id=a.team_id JOIN users u ON u.id=a.creator_id JOIN activity_teams ats ON ats.activity_id=a.id JOIN teams involved ON involved.id=ats.team_id LEFT JOIN tasks t ON t.activity_id=a.id LEFT JOIN participants p ON p.activity_id=a.id AND p.state='confirmed' LEFT JOIN updates n ON n.activity_id=a.id WHERE ${s.sql} AND a.status='completed' AND (a.title LIKE ? OR a.description LIKE ? OR COALESCE(a.result_summary,'') LIKE ?) GROUP BY a.id ORDER BY a.deadline DESC`,[...s.params,q,q,q]);res.json(rows)}));

router.get('/api/reports/export',auth,manager,asyncRoute(async(req,res)=>{
  const start=String(req.query.start||''),end=String(req.query.end||''),teamId=Number(req.query.team_id||0);
  const vietnamese=req.query.lang==='vi',reportLabels={Activities:'Hoạt động',Activity:'Hoạt động',Type:'Loại',Status:'Trạng thái','Start date':'Ngày bắt đầu',Deadline:'Hạn hoàn thành',Priority:'Mức ưu tiên','Coordinating team':'Tổ chủ trì','Involved teams':'Các Tổ tham gia',Tasks:'Công việc','Completed tasks':'Công việc hoàn thành',Participants:'Người tham gia','Team members':'Thành viên Tổ',Team:'Tổ',Member:'Thành viên',Email:'Email',Role:'Vai trò','Assigned tasks':'Công việc được giao','Confirmed activities':'Hoạt động đã xác nhận','Volunteered activities':'Hoạt động đã đăng ký','Member contributions':'Đóng góp của thành viên','Activity status':'Trạng thái hoạt động',Task:'Công việc','Task status':'Trạng thái công việc','Task deadline':'Hạn công việc','Completed at':'Thời điểm hoàn thành',Participation:'Tham gia',Responsibility:'Nhiệm vụ'},valueLabels={event:'sự kiện',assigned:'được giao',proposed:'đề xuất',approved:'đã duyệt',active:'đang hoạt động',completed:'hoàn thành',cancelled:'đã hủy',low:'thấp',medium:'trung bình',high:'cao',urgent:'khẩn cấp',open:'đang mở',in_progress:'đang thực hiện',review:'đang duyệt',done:'hoàn thành',confirmed:'đã xác nhận',volunteered:'đã đăng ký',admin:'Trưởng Ban',vice_admin:'Phó Ban',leader:'Tổ trưởng',vice_leader:'Tổ phó',lecturer:'giảng viên',member:'Thành viên'};
  const h=label=>vietnamese?(reportLabels[label]||label):label,localizedFields=new Set(['type','status','priority','role','activity_status','task_status','participation_state']),localizeRows=rows=>vietnamese?rows.map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,localizedFields.has(key)?valueLabels[value]||value:value]))):rows;
  const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value;
  if(!validDate(start)||!validDate(end)||start>end)return res.status(400).json({error:'Choose a valid report date range.'});
  const allowedTeams=await managedTeamIds(req.actor);
  if(teamId&&(!Number.isInteger(teamId)||!allowedTeams.includes(teamId)))return res.status(403).json({error:'You cannot export a report for this team.'});
  const reportTeams=teamId?[teamId]:allowedTeams;
  if(!reportTeams.length)return res.status(400).json({error:'No reportable teams are available.'});
  const marks=reportTeams.map(()=>'?').join(','),dateParams=[end,start],teamParams=[...reportTeams];
  const [[activities],[members],[contributions]]=await Promise.all([
    db.execute(`SELECT a.id,a.title,a.type,a.status,a.start_date,a.deadline,a.priority,primary_team.name coordinating_team,GROUP_CONCAT(DISTINCT involved.name ORDER BY involved.name SEPARATOR ', ') involved_teams,COUNT(DISTINCT tk.id) task_count,COUNT(DISTINCT CASE WHEN tk.status='done' THEN tk.id END) completed_tasks,COUNT(DISTINCT CASE WHEN p.state='confirmed' THEN p.user_id END) confirmed_participants FROM activities a JOIN teams primary_team ON primary_team.id=a.team_id JOIN activity_teams at_scope ON at_scope.activity_id=a.id AND at_scope.team_id IN (${marks}) JOIN activity_teams at_all ON at_all.activity_id=a.id JOIN teams involved ON involved.id=at_all.team_id LEFT JOIN tasks tk ON tk.activity_id=a.id LEFT JOIN participants p ON p.activity_id=a.id WHERE COALESCE(a.start_date,a.deadline)<=? AND a.deadline>=? GROUP BY a.id ORDER BY a.deadline,a.title`,[...teamParams,...dateParams]),
    db.execute(`SELECT team.name team_name,u.name member_name,u.email,u.role,COUNT(DISTINCT tk.id) assigned_tasks,COUNT(DISTINCT CASE WHEN tk.status='done' THEN tk.id END) completed_tasks,COUNT(DISTINCT CASE WHEN p.state='confirmed' THEN p.activity_id END) confirmed_activities,COUNT(DISTINCT CASE WHEN p.state='volunteered' THEN p.activity_id END) volunteered_activities FROM user_teams ut JOIN teams team ON team.id=ut.team_id JOIN users u ON u.id=ut.user_id LEFT JOIN task_assignees ta ON ta.user_id=u.id LEFT JOIN tasks tk ON tk.id=ta.task_id AND tk.team_id=ut.team_id AND EXISTS(SELECT 1 FROM activities task_activity WHERE task_activity.id=tk.activity_id AND COALESCE(task_activity.start_date,task_activity.deadline)<=? AND task_activity.deadline>=?) LEFT JOIN participants p ON p.user_id=u.id AND p.state!='declined' AND EXISTS(SELECT 1 FROM activities participant_activity WHERE participant_activity.id=p.activity_id AND COALESCE(participant_activity.start_date,participant_activity.deadline)<=? AND participant_activity.deadline>=?) WHERE ut.team_id IN (${marks}) AND u.is_active=1 GROUP BY ut.team_id,u.id ORDER BY team.name,u.name`,[...dateParams,...dateParams,...teamParams]),
    db.execute(`SELECT team.name team_name,u.name member_name,u.email,u.role,a.title activity_title,a.status activity_status,tk.title task_title,tk.status task_status,tk.deadline task_deadline,tk.completed_at,p.state participation_state,p.responsibility FROM user_teams ut JOIN teams team ON team.id=ut.team_id JOIN users u ON u.id=ut.user_id JOIN activities a ON COALESCE(a.start_date,a.deadline)<=? AND a.deadline>=? AND (EXISTS(SELECT 1 FROM tasks scoped_task JOIN task_assignees scoped_assignee ON scoped_assignee.task_id=scoped_task.id WHERE scoped_task.activity_id=a.id AND scoped_task.team_id=ut.team_id AND scoped_assignee.user_id=u.id) OR EXISTS(SELECT 1 FROM participants scoped_participant WHERE scoped_participant.activity_id=a.id AND scoped_participant.user_id=u.id AND scoped_participant.state!='declined')) LEFT JOIN tasks tk ON tk.activity_id=a.id AND tk.team_id=ut.team_id AND EXISTS(SELECT 1 FROM task_assignees assigned WHERE assigned.task_id=tk.id AND assigned.user_id=u.id) LEFT JOIN participants p ON p.activity_id=a.id AND p.user_id=u.id AND p.state!='declined' WHERE ut.team_id IN (${marks}) AND u.is_active=1 AND (tk.id IS NOT NULL OR p.user_id IS NOT NULL) GROUP BY ut.team_id,u.id,a.id,tk.id,p.user_id ORDER BY team.name,u.name,a.deadline,tk.deadline`,[...dateParams,...teamParams])
  ]);
  const workbook=new ExcelJS.Workbook();workbook.creator='TCKT Activity Hub';workbook.created=new Date();
  const addSheet=(name,columns,rows)=>{const sheet=workbook.addWorksheet(name,{views:[{state:'frozen',ySplit:1}]});sheet.columns=columns.map(([header,key,width])=>({header,key,width}));rows.forEach(row=>sheet.addRow(row));sheet.eachRow(row=>row.eachCell(cell=>{cell.font={name:'Arial',size:10}}));sheet.getRow(1).font={name:'Arial',size:10,bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1E3A8A'}};sheet.autoFilter={from:'A1',to:`${sheet.getColumn(columns.length).letter}1`};return sheet};
  addSheet(h('Activities'),[['Activity','title',34],['Type','type',14],['Status','status',14],['Start date','start_date',14],['Deadline','deadline',14],['Priority','priority',12],['Coordinating team','coordinating_team',24],['Involved teams','involved_teams',38],['Tasks','task_count',10],['Completed tasks','completed_tasks',16],['Participants','confirmed_participants',14]].map(([label,...rest])=>[h(label),...rest]),localizeRows(activities));
  addSheet(h('Team members'),[['Team','team_name',24],['Member','member_name',24],['Email','email',28],['Role','role',13],['Assigned tasks','assigned_tasks',15],['Completed tasks','completed_tasks',16],['Confirmed activities','confirmed_activities',19],['Volunteered activities','volunteered_activities',21]].map(([label,...rest])=>[h(label),...rest]),localizeRows(members));
  addSheet(h('Member contributions'),[['Team','team_name',24],['Member','member_name',24],['Email','email',28],['Role','role',13],['Activity','activity_title',34],['Activity status','activity_status',15],['Task','task_title',34],['Task status','task_status',14],['Task deadline','task_deadline',15],['Completed at','completed_at',19],['Participation','participation_state',15],['Responsibility','responsibility',28]].map(([label,...rest])=>[h(label),...rest]),localizeRows(contributions));
  const buffer=await workbook.xlsx.writeBuffer(),teamLabel=teamId?`team-${teamId}`:'all-teams';
  res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="tckt-report-${teamLabel}-${start}-to-${end}.xlsx"`);res.send(Buffer.from(buffer));
}));

  return router;
}

module.exports = { createReportRoutes };
