key: task.overdue
subject: "[{{ activity.title }}] {{ task.title }}"
required:
  - task.id
  - task.title
  - task.path
  - activity.title
optional:
  - task.deadline
data_example:
  task:
    id: 120
    title: "Làm poster hoạt động"
    path: "/#activity/3"
    deadline: "2026-10-01 17:00"
  activity:
    title: "Tập huấn cán bộ Đoàn"
