"""khoi tao bang

Revision ID: 82104b016f3b
Revises: 
Create Date: 2026-09-16 10:36:43.107431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82104b016f3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('document_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('applies_to', sa.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('allow_not_applicable', sa.Boolean(), nullable=False),
    sa.Column('accepted_ext', sa.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('max_size_mb', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('otp_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_code_email'), 'otp_code', ['email'], unique=False)
    op.create_table('status_def',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('holder_role', sa.String(length=20), nullable=True),
    sa.Column('sla_days', sa.Integer(), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('DOAN_TRUONG', 'LIEN_CHI_DOAN', 'TCKT', 'VP_DOAN', name='unitkind', native_enum=False, length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SINH_VIEN', 'CAN_BO_DON_VI', 'TCKT', 'VP_DOAN', 'CHI_BO', 'QUAN_TRI', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('transition_def',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('action_code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('allowed_roles', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('requires_reason', sa.Boolean(), nullable=False),
    sa.Column('event_code', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['from_status'], ['status_def.code'], ),
    sa.ForeignKeyConstraint(['to_status'], ['status_def.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_status', 'action_code', name='uq_transition_from_action')
    )
    op.create_index(op.f('ix_transition_def_action_code'), 'transition_def', ['action_code'], unique=False)
    op.create_index(op.f('ix_transition_def_from_status'), 'transition_def', ['from_status'], unique=False)
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('case_type', sa.Enum('KET_NAP', 'CHUYEN_CHINH_THUC', name='casetype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('state_entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status_def.code'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_case_applicant_id'), 'case', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_case_batch_id'), 'case', ['batch_id'], unique=False)
    op.create_index(op.f('ix_case_status'), 'case', ['status'], unique=False)
    op.create_index(op.f('ix_case_unit_id'), 'case', ['unit_id'], unique=False)
    op.create_index('uq_case_one_active_per_applicant', 'case', ['applicant_id'], unique=True, postgresql_where=sa.text("status NOT IN ('forwarded', 'cancelled')"))
    op.create_table('case_detail',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('personal_email', sa.String(length=255), nullable=False),
    sa.Column('citizen_id', sa.String(length=12), nullable=False),
    sa.Column('permanent_address', sa.Text(), nullable=False),
    sa.Column('temp_address', sa.Text(), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=False),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=10), nullable=False),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('conduct_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('case_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('action_code', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_event_case_id'), 'case_event', ['case_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('MISSING', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'NOT_APPLICABLE', name='docstatus', native_enum=False, length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('allow_not_applicable', sa.Boolean(), nullable=False),
    sa.Column('is_adhoc', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_case_id'), 'document', ['case_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('to_emails', sa.Text(), nullable=False),
    sa.Column('cc_emails', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event_code', sa.String(length=40), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index(op.f('ix_outbox_case_id'), 'outbox', ['case_id'], unique=False)
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_case_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_document_case_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_case_event_case_id'), table_name='case_event')
    op.drop_table('case_event')
    op.drop_table('case_detail')
    op.drop_index('uq_case_one_active_per_applicant', table_name='case', postgresql_where=sa.text("status NOT IN ('forwarded', 'cancelled')"))
    op.drop_index(op.f('ix_case_unit_id'), table_name='case')
    op.drop_index(op.f('ix_case_status'), table_name='case')
    op.drop_index(op.f('ix_case_batch_id'), table_name='case')
    op.drop_index(op.f('ix_case_applicant_id'), table_name='case')
    op.drop_table('case')
    op.drop_index(op.f('ix_transition_def_from_status'), table_name='transition_def')
    op.drop_index(op.f('ix_transition_def_action_code'), table_name='transition_def')
    op.drop_table('transition_def')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('unit')
    op.drop_table('status_def')
    op.drop_index(op.f('ix_otp_code_email'), table_name='otp_code')
    op.drop_table('otp_code')
    op.drop_table('document_type')
    op.drop_table('batch')
    # ### end Alembic commands ###
